application: aliceprofile
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /933090e2fb03b6da782f6a6adcfc949e.txt
  static_files: 933090e2fb03b6da782f6a6adcfc949e.txt
  upload: 933090e2fb03b6da782f6a6adcfc949e.txt

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest

builtins:
- remote_api: on

